/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void guiDraw(PApplet appc, GWinData data) { //_CODE_:gui:894024:
  appc.background(230);
} //_CODE_:gui:894024:

public void shapeTypeListClick(GDropList source, GEvent event) { //_CODE_:shapeTypeList:593435:
  println("shapeTypeList - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:shapeTypeList:593435:

public void addShapeButtonClick(GButton source, GEvent event) { //_CODE_:addShapeButton:557350:
  println("addShapeButton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:addShapeButton:557350:

public void removeShapeButtonClick(GButton source, GEvent event) { //_CODE_:removeShapeButton:980011:
  println("removeShapeButton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:removeShapeButton:980011:

public void greenSliderClick(GCustomSlider source, GEvent event) { //_CODE_:greenSlider:386541:
  println("greenSlider - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:greenSlider:386541:

public void blueSliderChange(GCustomSlider source, GEvent event) { //_CODE_:blueSlider:699806:
  println("blueSlider - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:blueSlider:699806:

public void redSliderChange(GCustomSlider source, GEvent event) { //_CODE_:redSlider:415599:
  println("redSlider - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:redSlider:415599:

synchronized public void tutDraw(PApplet appc, GWinData data) { //_CODE_:tutorial:852036:
  appc.background(230);
} //_CODE_:tutorial:852036:

public void nextClicked(GButton source, GEvent event) { //_CODE_:next:783622:
  tutPage += 1;
} //_CODE_:next:783622:

public void backClicked(GButton source, GEvent event) { //_CODE_:back:491218:
  tutPage -= 1;
} //_CODE_:back:491218:

public void finishClicked(GButton source, GEvent event) { //_CODE_:finish:597876:
  tutorialShow = false;
} //_CODE_:finish:597876:

synchronized public void startWinDraw(PApplet appc, GWinData data) { //_CODE_:startWin:587259:
  appc.background(230);
} //_CODE_:startWin:587259:

public void startClicked(GButton source, GEvent event) { //_CODE_:start:897298:
  windowName = "Create";
} //_CODE_:start:897298:

public void tutButtonClicked(GButton source, GEvent event) { //_CODE_:tutButton:584753:
  tutPage = 1;
  tutorialShow = true;
} //_CODE_:tutButton:584753:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Modello");
  gui = GWindow.getWindow(this, "GUI", 0, 0, 240, 150, JAVA2D);
  gui.noLoop();
  gui.setActionOnClose(G4P.KEEP_OPEN);
  gui.addDrawHandler(this, "guiDraw");
  shapeTypeList = new GDropList(gui, 10, 9, 90, 80, 3, 10);
  shapeTypeList.setItems(loadStrings("list_593435"), 0);
  shapeTypeList.addEventHandler(this, "shapeTypeListClick");
  addShapeButton = new GButton(gui, 15, 44, 80, 30);
  addShapeButton.setText("Add Shape");
  addShapeButton.addEventHandler(this, "addShapeButtonClick");
  removeShapeButton = new GButton(gui, 14, 87, 80, 30);
  removeShapeButton.setText("Remove Shape");
  removeShapeButton.addEventHandler(this, "removeShapeButtonClick");
  label1 = new GLabel(gui, 112, 6, 80, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Colour Sliders");
  label1.setOpaque(false);
  greenSlider = new GCustomSlider(gui, 112, 48, 100, 40, "grey_blue");
  greenSlider.setLimits(0.0, 0.0, 255.0);
  greenSlider.setNumberFormat(G4P.DECIMAL, 2);
  greenSlider.setOpaque(false);
  greenSlider.addEventHandler(this, "greenSliderClick");
  blueSlider = new GCustomSlider(gui, 112, 72, 100, 40, "grey_blue");
  blueSlider.setLimits(0.0, 0.0, 255.0);
  blueSlider.setNumberFormat(G4P.DECIMAL, 2);
  blueSlider.setOpaque(false);
  blueSlider.addEventHandler(this, "blueSliderChange");
  redSlider = new GCustomSlider(gui, 112, 25, 100, 40, "grey_blue");
  redSlider.setLimits(255.0, 0.0, 255.0);
  redSlider.setNumberFormat(G4P.DECIMAL, 2);
  redSlider.setOpaque(false);
  redSlider.addEventHandler(this, "redSliderChange");
  tutorial = GWindow.getWindow(this, "Tutorial", 0, 0, 480, 240, JAVA2D);
  tutorial.noLoop();
  tutorial.setActionOnClose(G4P.KEEP_OPEN);
  tutorial.addDrawHandler(this, "tutDraw");
  next = new GButton(tutorial, 400, 190, 60, 30);
  next.setText("next");
  next.addEventHandler(this, "nextClicked");
  back = new GButton(tutorial, 30, 190, 60, 30);
  back.setText("back");
  back.addEventHandler(this, "backClicked");
  finish = new GButton(tutorial, 200, 190, 90, 30);
  finish.setText("finish");
  finish.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  finish.addEventHandler(this, "finishClicked");
  startWin = GWindow.getWindow(this, "Modello", 0, 0, 500, 400, JAVA2D);
  startWin.noLoop();
  startWin.setActionOnClose(G4P.KEEP_OPEN);
  startWin.addDrawHandler(this, "startWinDraw");
  start = new GButton(startWin, 210, 170, 80, 30);
  start.setText("START");
  start.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  start.addEventHandler(this, "startClicked");
  tutButton = new GButton(startWin, 210, 230, 80, 30);
  tutButton.setText("Tutorial");
  tutButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  tutButton.addEventHandler(this, "tutButtonClicked");
  gui.loop();
  tutorial.loop();
  startWin.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow gui;
GDropList shapeTypeList; 
GButton addShapeButton; 
GButton removeShapeButton; 
GLabel label1; 
GCustomSlider greenSlider; 
GCustomSlider blueSlider; 
GCustomSlider redSlider; 
GWindow tutorial;
GButton next; 
GButton back; 
GButton finish; 
GWindow startWin;
GButton start; 
GButton tutButton; 
