/* autogenerated by Processing revision 1307 on 2025-12-11 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import g4p_controls.*;
import java.io.File;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Modello extends PApplet {




String windowName = "Start";
Boolean tutorialShow = false;
Boolean libraryShow = false;
int tutPage = 1;
PFont titleFont;
int screenshotNum;
int numAddLib = 0;
String imageFileNum;
int iconX = 0;
int iconY = 0;
int drawn = 0;

//Shape currentShape;
PatternTile currentTile = new PatternTile();
Arrangement currentPattern;

ArrayList<Arrangement> Patterns; //complete patterns saved, might not be needed we will see
ArrayList<GImageButton> libraryImgs = new ArrayList(); //an arraylist that stores the saved images as icons

Boolean arrguiShow = false;

int savedPTilenum = 1;

int bgColour = color(100);

String TileStatus = "creating";

GImageButton title, loadPattern;

public void setup() {
  /* size commented out by preprocessor */;
  createGUI();
  frameRate(120);
  
  //sets these as false at the start of the program
  library.setVisible(false);
  tutorial.setVisible(false);
}


public void draw() {
  displayScreen();
  background(bgColour);

  imageMode(CENTER);

  if (!arrguiShow) {
    currentTile.drawTile();
  }

  if (arrguiShow) {
    background(bgColour);
    currentPattern.drawPattern();
  }
  
  if (TileStatus.equals("visualising")){
    VisualisePattern(currentTile);
  }
}

public void exit(){
  for (int i = 0; i <= numAddLib; i++){    
    File f = dataFile("libraryIcon"+i+".png");
    if (f.exists()){
      if (f.delete()){
        println(f, "deleted");
      }
      else{
        println(f, "not deleted");
      }
    }
    
    else{
      println(f, "doesn't exist");
    }
  }
  super.exit();
}
class Arrangement{
  
  float xSpacing;
  float ySpacing;
  
  PImage ATile;
  
  //ArrayList <PImage> ArrangedTiles = new ArrayList();
  
  PVector pos;

  float hsize;
  float wsize;
  
  String type;
 
  
  //*ignore* for personal reference, probably shapelayer1 = new arrangement(shape s)
  // and then buttons change it like shapelayer1.drawGrid() when the button clicked;
  // also note for img syntax its image(variable, posx, posy, hei, wid)
  
  Arrangement(){
    this.ATile = loadImage("SavedTile.png");
    this.xSpacing = 50;
    this.ySpacing = 50;
    this.pos = new PVector(0,0);
    this.hsize = 50;
    this.wsize = 50;
    
    this.type = "Grid";    
  }
  
  public void drawPattern(){
    //note: default arrangement is singular of the shape tile in middle of screen
    if (this.type.equals("default") || this.type.equals("Select"))
      this.defaultArrange();
    
    else if(this.type.equals("Grid"))
      this.drawGrid();
    
    else if(this.type.equals("Half-Drop"))
      this.drawHalfDrop();
    
    else if(this.type.equals("Brick"))
      this.drawBrick();
  }
  
  
  public void defaultArrange(){
    this.pos = new PVector( width/2, height/2) ; //maybe a 2d slider for this default one
    
    image(ATile, this.pos.x, this.pos.y, wsize, hsize);
    //assume there are sliders to change the shapes size, pos, colour, etc. in this scenario
  }
  
  
  public void drawGrid(){
    int xnum = ceil(width/xSpacing);
    int ynum = ceil(height/ySpacing);
    
  
    
    for (int i = 0; i < xnum; i++){
      for(int j = 0; j < ynum; j++){
        float xPos = i*this.xSpacing + this.wsize/2.0f;
        float yPos = j*this.ySpacing + this.hsize/2.0f;
       
        
        image(ATile, xPos, yPos, wsize, hsize);
        }
      }
    }
    
   public void drawHalfDrop(){
    int xnum = ceil(width/xSpacing);
    int ynum = ceil(height/ySpacing) + 1;
    
    
    
    for (int i = 0; i < xnum; i++){
      for(int j = 0; j < ynum; j++){
        
        float xPos = i*this.xSpacing + this.wsize/2.0f;
        float yPos = j*this.ySpacing ; 
        
        if (i % 2 == 1){
          yPos += this.hsize/2;
        }
        
        image(ATile, xPos, yPos, wsize, hsize);
        }
      }
   }
   
   public void drawBrick(){
    int xnum = ceil(width/xSpacing) + 1;
    int ynum = ceil(height/ySpacing);
    
    
    for (int i = 0; i < xnum; i++){
      for(int j = 0; j < ynum; j++){
        
        float xPos = i*this.xSpacing;
        float yPos = j*this.ySpacing + this.hsize/2.0f;
        
        if (j % 2 == 1){
          xPos += this.wsize/2.0f;
        }
        
        image(ATile, xPos, yPos, wsize, hsize);
        }
      }
   }
  
 
}

public void getShapeValues(Shape s) {
  s.type = shapeTypeList.getSelectedText();
  int r = redSlider.getValueI();
  int g = greenSlider.getValueI();
  int b = blueSlider.getValueI();
  s.colour = color(r, g, b);

  s.hei = heightSlider.getValueI();
  s.wid = widthSlider.getValueI();
}

public void changeShapeValues() {
  for (int i = 0; i < currentTile.ArrangedShapes.size(); i++) {
    Shape testShape = currentTile.ArrangedShapes.get(i);
    if (testShape.isSelected) {
      getShapeValues(testShape);
    }
  }
}

public void changeBgColour() {
  int r = bgRedSlider.getValueI();
  int g = bgGreenSlider.getValueI();
  int b = bgBlueSlider.getValueI();
  
  bgColour = color(r, g, b);

}

public void changeArrangementValues(Arrangement a) {
  a.type = arrTypedroplist.getSelectedText();
  
  float xspacingval = X_Spacing.getValueF();
  if (xspacingval > a.wsize){
    a.xSpacing = xspacingval;
  }
  else{
    a.xSpacing = a.wsize;
    X_Spacing.setValue(a.wsize);
  }
  float yspacingval = Y_Spacing.getValueF();
  if (yspacingval > a.hsize){
    a.ySpacing = yspacingval;
  }
  else{
    a.ySpacing = a.hsize;
    Y_Spacing.setValue(a.hsize);
  }

  a.hsize = arrheightslider.getValueI();
  a.wsize = arrwidthslider.getValueI();
}

public void VisualisePattern(PatternTile p){  
  if (TileStatus.equals("preparing")){
    p.seeGrid = false;
    gridButton.setSelected(false);
    
    TileStatus = "visualising";
  }
  
  else if(TileStatus.equals("visualising")){
    saveFrame("SavedTile.png");
    currentPattern = new Arrangement();
    
    ArrGUI.setVisible(true);
    arrguiShow = true;
    
    gui.setVisible(false);
    arrTypedroplist.setSelected(1);
    
    TileStatus = "creating";
  }
}

//math the icon locations
public void iconLocation(){
  iconX++;
  if (iconX >= 4){
    iconX = 0;
    iconY++;
  }
}

//event handler. This sets what happens when the user clicks on the buttons in library
public void handleButtonEvents(GImageButton source, GEvent event) {
  if (event == GEvent.CLICKED) {
    for (int i = 0; i <= numAddLib; i++){
      if (source == libraryImgs.get(i)){
        println("button", i, "clicked");
      }
    }
  }
}

boolean onObject = false;
PVector mousePos;

public void mouseClicked() {
  mousePos = new PVector(mouseX, mouseY);
  for (int i = currentTile.ArrangedShapes.size() - 1; i >=0 ; i--) { 
    Shape testShape = currentTile.ArrangedShapes.get(i);
    if (testShape.inShape(mousePos)) {
      onObject = true;
      testShape.isSelected = true;
      break;
    }
  }
}

public void mouseDragged() {
  mousePos = new PVector(mouseX, mouseY);
  for (int i = 0; i < currentTile.ArrangedShapes.size(); i++) {
    Shape testShape = currentTile.ArrangedShapes.get(i);
    if (testShape.isSelected && onObject) {
      testShape.pos = mousePos;
    }
  }
}

public void mouseReleased() {
  mousePos = new PVector(mouseX, mouseY);
  for (int i = 0; i < currentTile.ArrangedShapes.size(); i++) {
    Shape testShape = currentTile.ArrangedShapes.get(i);
    if (testShape.isSelected) {
      onObject = false;
      testShape.isSelected = false;
    }
  }
}

class PatternTile {
  //fields
  ArrayList <Shape> ArrangedShapes;
  boolean seeGrid, autoAlign;
  float gridSize;

  //constructor
  PatternTile() {
    this.ArrangedShapes = new ArrayList();
    this.seeGrid = false;
    this.autoAlign = false;
    this.gridSize = 25;
  }

  //methods
  public void drawTile() {
    if (seeGrid) drawGrid();
    for (int i = 0; i < this.ArrangedShapes.size(); i++) {
      if (autoAlign) autoAlign();

      this.ArrangedShapes.get(i).drawShape();
    }
  }

  public void drawGrid() {
    stroke(180);

    for (int x = 0; x <= width; x += this.gridSize) {
      line(x, 0, x, height);
    }
    for (int y = 0; y <= height; y += this.gridSize) {
      line(0, y, width, y);
    }
  }

  public void autoAlign() {    
    for (Shape s : currentTile.ArrangedShapes) {

      float nearestX = round(s.pos.x / this.gridSize) * this.gridSize;
      float nearestY = round(s.pos.y / this.gridSize) * this.gridSize;

      float dx = abs(nearestX - s.pos.x);
      float dy = abs(nearestY - s.pos.y);

      if (abs(dx - dy) < 1.5f) {
        s.pos.x = nearestX;
        s.pos.y = nearestY;
      } else if (dx < dy) {
        s.pos.x = nearestX;
      } else {
        s.pos.y = nearestY;
      }
    }
  }
}
//Function creates the different windows

public void displayScreen(){
  fill(0);
  
  //(idk this is a placeholder for now cuz gui not drawn)
  //Start screen
  if (windowName.equals("Start")){
    surface.setVisible(false);
    tutButton.setVisible(true);
    gui.setVisible(false);
    ArrGUI.setVisible(false);
    startWin.setVisible(true);
    
    title = new GImageButton(startWin, 80, 34, 333, 156, new String[] { "MODELLO.png" } );
    
    windowName = "none";
  }
  
  //"Create" screen is the screen which the user will create the pattern
  else if (windowName.equals("Create")){
    gui.setVisible(true);
    surface.setVisible(true);
    startWin.setVisible(false);
    
    //we set the window to none because when we set the visibility multiple times, it causes the screen to flash
    windowName = "none";
    
  }
  
  //Users can see all their saved patterns together
  if (libraryShow == true){
    library.setVisible(true);
    
    //for loop to add all the images
    imageFileNum = "libraryIcon"+numAddLib+".png";
    
    for(int i = 0; i <= iconY+1; i++){
      for (int j = 0; j <= iconX+1;  j++){
        if (drawn < numAddLib){
          libraryImgs.get(4*i+j);
          drawn++;
        }
        else{
          
          return;
        }
        
        //loadPattern.addEventHandler(library, "loadPatternClicked");
      }
    }
    
  }
  else{
    library.setVisible(false);
  }
  
  //Basic tutorial on how to use the program
  //    Create second window(popup)
  if (tutorialShow == true){
    tutorial.setVisible(true);
    //first tutorial page
    if (tutPage == 1){
      next.setVisible(true);
      back.setVisible(false);
      finish.setVisible(false);
    }
    //second tutorial page
    else if (tutPage == 2){
      next.setVisible(true);
      back.setVisible(true);
      finish.setVisible(false);
    }
    //last tutorial page
    else{
      next.setVisible(false);
      back.setVisible(true);
      finish.setVisible(true);
    }
    
    
  }
  else{
    //tutorial closed
    tutorial.setVisible(false);
  }
  
}

class Shape {
  //fields
  String type;
  PVector pos;
  int hei, wid;
  int colour, strokeColor;
  boolean isSelected;
  float x1, y1, x2, y2, x3, y3;

  //constructor
  Shape(String t, PVector p, int h, int w, int r, int g, int b) {
    this.type = t;
    this.pos = p;
    this.hei = h;
    this.wid = w;
    this.colour = color(r, g, b);
    this.strokeColor = this.colour;
    this.isSelected = false;
  }

  //methods
  public void drawShape() {  
    stayInTile();
    if (isSelected) {
      this.strokeColor = color(255, 255, 0);
    } else {
      this.strokeColor = this.colour;
    }
    stroke(this.strokeColor);
    fill(this.colour);
    rectMode(CENTER);

    if (this.type.equals("ellipse")) {
      ellipse(this.pos.x, this.pos.y, this.wid, this.hei);
    } else if (this.type.equals("rectangle")) {
      rect(this.pos.x, this.pos.y, this.wid, this.hei);
      
    } else if (this.type.equals("triangle")) {
      x1 = this.pos.x - this.wid/2;
      y1 = this.pos.y + this.hei/2;
      x2 = this.pos.x;
      y2 = this.pos.y - this.hei/2;
      x3 = this.pos.x + this.wid/2;
      y3 = this.pos.y + this.hei/2;
      triangle(x1, y1, x2, y2, x3, y3);
    }
  }

  public boolean inShape(PVector p) {
    if (this.type.equals("ellipse")) {
      return (pow((p.x - this.pos.x), 2)/pow(this.wid/2, 2)) + (pow((p.y - this.pos.y), 2)/pow(this.hei/2, 2)) <= 1;
      
    } else if (this.type.equals("rectangle")) {
      return p.x < this.pos.x + this.wid/2
        && p.x > this.pos.x - this.wid/2
        && p.y < this.pos.y + this.hei/2
        && p.y > this.pos.y - this.hei/2;
        
    } else if (this.type.equals("triangle")) {
      PVector[] poly = new PVector[3];
      PVector[] sides = new PVector[3];
      PVector[] perpSides = new PVector[3];

      poly[0] = new PVector(x1, y1);
      poly[1] = new PVector(x2, y2);
      poly[2] = new PVector(x3, y3);

      for (int i = 0; i < 3; i++) {
        sides[i] = PVector.sub(poly[(i+1)%3], poly[i]);
        perpSides[i] = new PVector(-sides[i].y, sides[i].x);
      }

      boolean in = true;

      for (int i = 0; i < 3; i++) {
        PVector v1 = PVector.sub(p, poly[i]);
        float dotProd = v1.dot(perpSides[i]);
        if ( dotProd < 0 ) in = false;
      }      
      return in;
    } else return false;
  }
  
  public void stayInTile() {
    if (this.pos.x > width) this.pos.x = width;
    else if (this.pos.x < 0) this.pos.x = 0;
    else if (this.pos.y > height) this.pos.y = height;
    else if (this.pos.y < 0) this.pos.y = 0;
  }
}
/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void guiDraw(PApplet appc, GWinData data) { //_CODE_:gui:894024:
  appc.background(230);
} //_CODE_:gui:894024:

public void shapeTypeListClick(GDropList source, GEvent event) { //_CODE_:shapeTypeList:593435:
  changeShapeValues();
} //_CODE_:shapeTypeList:593435:

public void addShapeButtonClick(GButton source, GEvent event) { //_CODE_:addShapeButton:557350:
  Shape newShape = new Shape("ellipse", new PVector(250, 250), 50, 100, 200, 0, 0);
  getShapeValues(newShape);
  this.currentTile.ArrangedShapes.add(newShape);
} //_CODE_:addShapeButton:557350:

public void removeShapeButtonClick(GButton source, GEvent event) { //_CODE_:removeShapeButton:980011:
  for (int i = 0; i < currentTile.ArrangedShapes.size(); i++) {
    Shape testShape = currentTile.ArrangedShapes.get(i);
    if (testShape.isSelected) {
      currentTile.ArrangedShapes.remove(testShape);
    }
  }
} //_CODE_:removeShapeButton:980011:

public void greenSliderClick(GCustomSlider source, GEvent event) { //_CODE_:greenSlider:386541:
  changeShapeValues();
} //_CODE_:greenSlider:386541:

public void blueSliderChange(GCustomSlider source, GEvent event) { //_CODE_:blueSlider:699806:
  changeShapeValues();
} //_CODE_:blueSlider:699806:

public void redSliderChange(GCustomSlider source, GEvent event) { //_CODE_:redSlider:415599:
  changeShapeValues();
  //title.
} //_CODE_:redSlider:415599:

public void tilescreenshot(GButton source, GEvent event) { //_CODE_:savetilebutton:575000:
  TileStatus = "preparing";
  VisualisePattern(currentTile);
} //_CODE_:savetilebutton:575000:

public void widthSliderChange(GCustomSlider source, GEvent event) { //_CODE_:widthSlider:844943:
  changeShapeValues();
} //_CODE_:widthSlider:844943:

public void heightSliderChange(GCustomSlider source, GEvent event) { //_CODE_:heightSlider:256807:
  changeShapeValues();
} //_CODE_:heightSlider:256807:

public void gridClicked(GCheckbox source, GEvent event) { //_CODE_:gridButton:487609:
  if (! currentTile.seeGrid) {
    currentTile.seeGrid = true;
  } else currentTile.seeGrid = false;
} //_CODE_:gridButton:487609:

public void clearButtonClick(GButton source, GEvent event) { //_CODE_:clearButton:526941:
  currentTile.ArrangedShapes.clear();
} //_CODE_:clearButton:526941:

public void autoAlignClicked(GCheckbox source, GEvent event) { //_CODE_:autoAlign:584859:
  if (! currentTile.autoAlign) {
    currentTile.autoAlign = true;
  } else currentTile.autoAlign = false;
} //_CODE_:autoAlign:584859:

public void bgRedSliderChange(GCustomSlider source, GEvent event) { //_CODE_:bgRedSlider:713595:
  changeBgColour();
} //_CODE_:bgRedSlider:713595:

public void bgGreenSliderChange(GCustomSlider source, GEvent event) { //_CODE_:bgGreenSlider:262593:
  changeBgColour();
} //_CODE_:bgGreenSlider:262593:

public void bgBlueSliderChange(GCustomSlider source, GEvent event) { //_CODE_:bgBlueSlider:417099:
  changeBgColour();
} //_CODE_:bgBlueSlider:417099:

public void fwdShapeButtonClick(GButton source, GEvent event) { //_CODE_:fwdShapeButton:317310:
  for (int i = 0; i < currentTile.ArrangedShapes.size(); i++) {
    Shape fwdShape = currentTile.ArrangedShapes.get(i);
    
    if (fwdShape.isSelected && i < currentTile.ArrangedShapes.size() - 1) {
      Shape bckShape = currentTile.ArrangedShapes.get(i+1);
      currentTile.ArrangedShapes.set(i, bckShape);
      currentTile.ArrangedShapes.set(i+1, fwdShape);
    }
  }
} //_CODE_:fwdShapeButton:317310:

public void bwkShapeButtonClicked(GButton source, GEvent event) { //_CODE_:bwkShapeButton:867870:
  for (int i = 0; i < currentTile.ArrangedShapes.size(); i++) {
    Shape bckShape = currentTile.ArrangedShapes.get(i);
    
    if (bckShape.isSelected && i > 0) {
      Shape fwdShape = currentTile.ArrangedShapes.get(i-1);
      currentTile.ArrangedShapes.set(i, fwdShape);
      currentTile.ArrangedShapes.set(i-1, bckShape);
    }
  }
} //_CODE_:bwkShapeButton:867870:

public void toStartClicked(GButton source, GEvent event) { //_CODE_:toStart:677194:
  windowName = "Start";
} //_CODE_:toStart:677194:

public void gridSliderChange(GCustomSlider source, GEvent event) { //_CODE_:gridSlider:954807:
  currentTile.gridSize = gridSlider.getValueI();;
} //_CODE_:gridSlider:954807:

synchronized public void tutDraw(PApplet appc, GWinData data) { //_CODE_:tutorial:852036:
  appc.background(230);
} //_CODE_:tutorial:852036:

public void nextClicked(GButton source, GEvent event) { //_CODE_:next:783622:
  tutPage += 1;
} //_CODE_:next:783622:

public void backClicked(GButton source, GEvent event) { //_CODE_:back:491218:
  tutPage -= 1;
} //_CODE_:back:491218:

public void finishClicked(GButton source, GEvent event) { //_CODE_:finish:597876:
  tutorialShow = false;
} //_CODE_:finish:597876:

synchronized public void startWinDraw(PApplet appc, GWinData data) { //_CODE_:startWin:587259:
  appc.background(230);
} //_CODE_:startWin:587259:

public void startClicked(GButton source, GEvent event) { //_CODE_:start:897298:
  windowName = "Create";
} //_CODE_:start:897298:

public void tutButtonClicked(GButton source, GEvent event) { //_CODE_:tutButton:584753:
  tutPage = 1;
  tutorialShow = true;
} //_CODE_:tutButton:584753:

public void libraryClicked(GButton source, GEvent event) { //_CODE_:libraryButton:312218:
  libraryShow = true;
} //_CODE_:libraryButton:312218:

public void exitClicked(GButton source, GEvent event) { //_CODE_:exit:855732:
  exit();
} //_CODE_:exit:855732:

synchronized public void libraryDraw(PApplet appc, GWinData data) { //_CODE_:library:358380:
  appc.background(230);
} //_CODE_:library:358380:

public void closeLibClicked(GButton source, GEvent event) { //_CODE_:closeLib:641587:
  libraryShow = false;
} //_CODE_:closeLib:641587:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:ArrGUI:776699:
  appc.background(230);
} //_CODE_:ArrGUI:776699:

public void guibackbutton_clicked(GButton source, GEvent event) { //_CODE_:aguiback:763192:
  //println("aguiback - GButton >> GEvent." + event + " @ " + millis());
  ArrGUI.setVisible(false);
  arrguiShow = false;
  
  gui.setVisible(true);
} //_CODE_:aguiback:763192:

public void arrdroplist_clicked(GDropList source, GEvent event) { //_CODE_:arrTypedroplist:757056:
  //println("arrTypedroplist - GDropList >> GEvent." + event + " @ " + millis());
  changeArrangementValues(currentPattern);
} //_CODE_:arrTypedroplist:757056:

public void arrxSpacing_slider(GCustomSlider source, GEvent event) { //_CODE_:X_Spacing:703950:

  changeArrangementValues(currentPattern);
} //_CODE_:X_Spacing:703950:

public void arrYSpacing_change1(GCustomSlider source, GEvent event) { //_CODE_:Y_Spacing:640983:
changeArrangementValues(currentPattern);
  
} //_CODE_:Y_Spacing:640983:

public void arrwidthslider_change1(GCustomSlider source, GEvent event) { //_CODE_:arrwidthslider:968973:
  changeArrangementValues(currentPattern);
} //_CODE_:arrwidthslider:968973:

public void arrheislider_change1(GCustomSlider source, GEvent event) { //_CODE_:arrheightslider:213641:
  changeArrangementValues(currentPattern);
} //_CODE_:arrheightslider:213641:

public void addLibraryButtonClicked(GButton source, GEvent event) { //_CODE_:addLibraryButton:544916:
  saveFrame(dataPath("libraryIcon"+numAddLib+".png"));
  imageFileNum = "libraryIcon"+numAddLib+".png";
  libraryImgs.add(new GImageButton(library, 56+100*iconX, 30+100*iconY, 75, 75, new String[] {imageFileNum} ));
  numAddLib++;
  iconLocation();
  
  
} //_CODE_:addLibraryButton:544916:

public void patternSaveClicked(GButton source, GEvent event) { //_CODE_:patternSave:520565:
  saveFrame("savedPhotos/photo " + screenshotNum + ".png");
  screenshotNum++;
} //_CODE_:patternSave:520565:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Modello");
  gui = GWindow.getWindow(this, "GUI", 100, 200, 420, 250, JAVA2D);
  gui.noLoop();
  gui.setActionOnClose(G4P.KEEP_OPEN);
  gui.addDrawHandler(this, "guiDraw");
  shapeTypeList = new GDropList(gui, 11, 8, 90, 80, 3, 10);
  shapeTypeList.setItems(loadStrings("list_593435"), 0);
  shapeTypeList.addEventHandler(this, "shapeTypeListClick");
  addShapeButton = new GButton(gui, 13, 43, 80, 30);
  addShapeButton.setText("Add Shape");
  addShapeButton.addEventHandler(this, "addShapeButtonClick");
  removeShapeButton = new GButton(gui, 13, 81, 80, 30);
  removeShapeButton.setText("Remove Shape");
  removeShapeButton.addEventHandler(this, "removeShapeButtonClick");
  label1 = new GLabel(gui, 120, 8, 80, 20);
  label1.setText("Colour Sliders");
  label1.setOpaque(false);
  greenSlider = new GCustomSlider(gui, 129, 52, 100, 40, "grey_blue");
  greenSlider.setLimits(0.0f, 0.0f, 255.0f);
  greenSlider.setNumberFormat(G4P.DECIMAL, 2);
  greenSlider.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  greenSlider.setOpaque(false);
  greenSlider.addEventHandler(this, "greenSliderClick");
  blueSlider = new GCustomSlider(gui, 129, 75, 100, 40, "grey_blue");
  blueSlider.setLimits(0.0f, 0.0f, 255.0f);
  blueSlider.setNumberFormat(G4P.DECIMAL, 2);
  blueSlider.setOpaque(false);
  blueSlider.addEventHandler(this, "blueSliderChange");
  redSlider = new GCustomSlider(gui, 129, 29, 100, 40, "grey_blue");
  redSlider.setLimits(255.0f, 0.0f, 255.0f);
  redSlider.setNumberFormat(G4P.DECIMAL, 2);
  redSlider.setLocalColorScheme(GCScheme.RED_SCHEME);
  redSlider.setOpaque(false);
  redSlider.addEventHandler(this, "redSliderChange");
  savetilebutton = new GButton(gui, 13, 173, 80, 30);
  savetilebutton.setText("Visualise Pattern!");
  savetilebutton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  savetilebutton.addEventHandler(this, "tilescreenshot");
  widthSlider = new GCustomSlider(gui, 281, 19, 100, 40, "grey_blue");
  widthSlider.setLimits(100.0f, 0.0f, 500.0f);
  widthSlider.setNumberFormat(G4P.DECIMAL, 2);
  widthSlider.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  widthSlider.setOpaque(false);
  widthSlider.addEventHandler(this, "widthSliderChange");
  heightSlider = new GCustomSlider(gui, 281, 41, 100, 40, "grey_blue");
  heightSlider.setLimits(100.0f, 0.0f, 500.0f);
  heightSlider.setNumberFormat(G4P.DECIMAL, 2);
  heightSlider.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  heightSlider.setOpaque(false);
  heightSlider.addEventHandler(this, "heightSliderChange");
  label2 = new GLabel(gui, 243, 8, 80, 20);
  label2.setText("Size Sliders");
  label2.setOpaque(false);
  gridButton = new GCheckbox(gui, 242, 176, 120, 21);
  gridButton.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  gridButton.setText("See grid");
  gridButton.setOpaque(false);
  gridButton.addEventHandler(this, "gridClicked");
  clearButton = new GButton(gui, 13, 117, 80, 30);
  clearButton.setText("Clear Tile");
  clearButton.addEventHandler(this, "clearButtonClick");
  autoAlign = new GCheckbox(gui, 242, 156, 120, 20);
  autoAlign.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  autoAlign.setText("Allow auto align");
  autoAlign.setOpaque(false);
  autoAlign.addEventHandler(this, "autoAlignClicked");
  label3 = new GLabel(gui, 120, 126, 112, 29);
  label3.setText("Background Colour");
  label3.setOpaque(false);
  bgRedSlider = new GCustomSlider(gui, 129, 155, 100, 40, "grey_blue");
  bgRedSlider.setLimits(255, 0, 255);
  bgRedSlider.setNumberFormat(G4P.INTEGER, 0);
  bgRedSlider.setLocalColorScheme(GCScheme.RED_SCHEME);
  bgRedSlider.setOpaque(false);
  bgRedSlider.addEventHandler(this, "bgRedSliderChange");
  bgGreenSlider = new GCustomSlider(gui, 129, 178, 100, 40, "grey_blue");
  bgGreenSlider.setLimits(255, 0, 255);
  bgGreenSlider.setNumberFormat(G4P.INTEGER, 0);
  bgGreenSlider.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  bgGreenSlider.setOpaque(false);
  bgGreenSlider.addEventHandler(this, "bgGreenSliderChange");
  bgBlueSlider = new GCustomSlider(gui, 129, 201, 100, 40, "grey_blue");
  bgBlueSlider.setLimits(255, 0, 255);
  bgBlueSlider.setNumberFormat(G4P.INTEGER, 0);
  bgBlueSlider.setOpaque(false);
  bgBlueSlider.addEventHandler(this, "bgBlueSliderChange");
  fwdShapeButton = new GButton(gui, 241, 85, 143, 30);
  fwdShapeButton.setTextAlign(GAlign.CENTER, GAlign.RIGHT);
  fwdShapeButton.setText("Move Shape Forwards");
  fwdShapeButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  fwdShapeButton.addEventHandler(this, "fwdShapeButtonClick");
  bwkShapeButton = new GButton(gui, 241, 123, 143, 30);
  bwkShapeButton.setText("Move Shape Backwards");
  bwkShapeButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  bwkShapeButton.addEventHandler(this, "bwkShapeButtonClicked");
  label4 = new GLabel(gui, 109, 38, 20, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("R");
  label4.setOpaque(false);
  label5 = new GLabel(gui, 109, 61, 20, 20);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("G");
  label5.setOpaque(false);
  label6 = new GLabel(gui, 110, 86, 20, 20);
  label6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label6.setText("B");
  label6.setOpaque(false);
  toStart = new GButton(gui, 13, 213, 80, 30);
  toStart.setText("Return");
  toStart.setLocalColorScheme(GCScheme.RED_SCHEME);
  toStart.addEventHandler(this, "toStartClicked");
  label7 = new GLabel(gui, 243, 28, 80, 20);
  label7.setText("Width");
  label7.setOpaque(false);
  label8 = new GLabel(gui, 241, 52, 80, 20);
  label8.setText("Height");
  label8.setOpaque(false);
  label9 = new GLabel(gui, 109, 164, 19, 20);
  label9.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label9.setText("R");
  label9.setOpaque(false);
  label10 = new GLabel(gui, 107, 186, 22, 20);
  label10.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label10.setText("G");
  label10.setOpaque(false);
  label11 = new GLabel(gui, 109, 209, 20, 20);
  label11.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label11.setText("B");
  label11.setOpaque(false);
  gridSlider = new GCustomSlider(gui, 278, 201, 100, 40, "grey_blue");
  gridSlider.setLimits(25.0f, 10.0f, 50.0f);
  gridSlider.setNumberFormat(G4P.DECIMAL, 2);
  gridSlider.setOpaque(false);
  gridSlider.addEventHandler(this, "gridSliderChange");
  label12 = new GLabel(gui, 230, 204, 52, 28);
  label12.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label12.setText("Grid Size");
  label12.setOpaque(false);
  tutorial = GWindow.getWindow(this, "Tutorial", 0, 400, 480, 240, JAVA2D);
  tutorial.noLoop();
  tutorial.setActionOnClose(G4P.KEEP_OPEN);
  tutorial.addDrawHandler(this, "tutDraw");
  next = new GButton(tutorial, 400, 190, 60, 30);
  next.setText("next");
  next.addEventHandler(this, "nextClicked");
  back = new GButton(tutorial, 30, 190, 60, 30);
  back.setText("back");
  back.addEventHandler(this, "backClicked");
  finish = new GButton(tutorial, 200, 190, 90, 30);
  finish.setText("finish");
  finish.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  finish.addEventHandler(this, "finishClicked");
  startWin = GWindow.getWindow(this, "Modello", 500, 150, 500, 400, JAVA2D);
  startWin.noLoop();
  startWin.setActionOnClose(G4P.KEEP_OPEN);
  startWin.addDrawHandler(this, "startWinDraw");
  start = new GButton(startWin, 210, 170, 80, 30);
  start.setText("START");
  start.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  start.addEventHandler(this, "startClicked");
  tutButton = new GButton(startWin, 210, 230, 80, 30);
  tutButton.setText("Tutorial");
  tutButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  tutButton.addEventHandler(this, "tutButtonClicked");
  libraryButton = new GButton(startWin, 210, 290, 80, 30);
  libraryButton.setText("Library");
  libraryButton.addEventHandler(this, "libraryClicked");
  exit = new GButton(startWin, 210, 350, 80, 30);
  exit.setText("EXIT");
  exit.setLocalColorScheme(GCScheme.RED_SCHEME);
  exit.addEventHandler(this, "exitClicked");
  library = GWindow.getWindow(this, "Library", 1000, 400, 500, 400, JAVA2D);
  library.noLoop();
  library.setActionOnClose(G4P.KEEP_OPEN);
  library.addDrawHandler(this, "libraryDraw");
  closeLib = new GButton(library, 210, 290, 80, 30);
  closeLib.setText("CLOSE");
  closeLib.setLocalColorScheme(GCScheme.RED_SCHEME);
  closeLib.addEventHandler(this, "closeLibClicked");
  ArrGUI = GWindow.getWindow(this, "Window title", 100, 450, 280, 200, JAVA2D);
  ArrGUI.noLoop();
  ArrGUI.setActionOnClose(G4P.KEEP_OPEN);
  ArrGUI.addDrawHandler(this, "win_draw1");
  aguiback = new GButton(ArrGUI, 7, 152, 95, 30);
  aguiback.setText("Back to Canvas");
  aguiback.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  aguiback.addEventHandler(this, "guibackbutton_clicked");
  ArrangementType = new GLabel(ArrGUI, -2, 3, 125, 20);
  ArrangementType.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  ArrangementType.setText("Arrangement Type");
  ArrangementType.setOpaque(false);
  arrTypedroplist = new GDropList(ArrGUI, 10, 28, 90, 120, 5, 10);
  arrTypedroplist.setItems(loadStrings("list_757056"), 0);
  arrTypedroplist.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  arrTypedroplist.addEventHandler(this, "arrdroplist_clicked");
  X_Spacing = new GCustomSlider(ArrGUI, 135, 24, 100, 40, "grey_blue");
  X_Spacing.setLimits(50.0f, 0.0f, 500.0f);
  X_Spacing.setNumberFormat(G4P.GREEN_SCHEME, 2);
  X_Spacing.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  X_Spacing.setOpaque(false);
  X_Spacing.addEventHandler(this, "arrxSpacing_slider");
  Y_Spacing = new GCustomSlider(ArrGUI, 135, 48, 100, 40, "grey_blue");
  Y_Spacing.setLimits(50.0f, 0.0f, 500.0f);
  Y_Spacing.setNumberFormat(G4P.DECIMAL, 2);
  Y_Spacing.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  Y_Spacing.setOpaque(false);
  Y_Spacing.addEventHandler(this, "arrYSpacing_change1");
  Spacing_Labels = new GLabel(ArrGUI, 134, 5, 80, 20);
  Spacing_Labels.setText("Spacing");
  Spacing_Labels.setOpaque(false);
  SizeSliders = new GLabel(ArrGUI, 135, 89, 123, 20);
  SizeSliders.setText("Size ");
  SizeSliders.setOpaque(false);
  arrwidthslider = new GCustomSlider(ArrGUI, 134, 109, 100, 40, "grey_blue");
  arrwidthslider.setLimits(50.0f, 20.0f, 400.0f);
  arrwidthslider.setNumberFormat(G4P.DECIMAL, 2);
  arrwidthslider.setOpaque(false);
  arrwidthslider.addEventHandler(this, "arrwidthslider_change1");
  arrheightslider = new GCustomSlider(ArrGUI, 134, 132, 100, 40, "grey_blue");
  arrheightslider.setLimits(50.0f, 20.0f, 400.0f);
  arrheightslider.setNumberFormat(G4P.DECIMAL, 2);
  arrheightslider.setOpaque(false);
  arrheightslider.addEventHandler(this, "arrheislider_change1");
  addLibraryButton = new GButton(ArrGUI, 7, 114, 97, 30);
  addLibraryButton.setText("Add to Library");
  addLibraryButton.addEventHandler(this, "addLibraryButtonClicked");
  patternSave = new GButton(ArrGUI, 7, 77, 97, 30);
  patternSave.setText("Export Pattern");
  patternSave.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  patternSave.addEventHandler(this, "patternSaveClicked");
  gui.loop();
  tutorial.loop();
  startWin.loop();
  library.loop();
  ArrGUI.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow gui;
GDropList shapeTypeList; 
GButton addShapeButton; 
GButton removeShapeButton; 
GLabel label1; 
GCustomSlider greenSlider; 
GCustomSlider blueSlider; 
GCustomSlider redSlider; 
GButton savetilebutton; 
GCustomSlider widthSlider; 
GCustomSlider heightSlider; 
GLabel label2; 
GCheckbox gridButton; 
GButton clearButton; 
GCheckbox autoAlign; 
GLabel label3; 
GCustomSlider bgRedSlider; 
GCustomSlider bgGreenSlider; 
GCustomSlider bgBlueSlider; 
GButton fwdShapeButton; 
GButton bwkShapeButton; 
GLabel label4; 
GLabel label5; 
GLabel label6; 
GButton toStart; 
GLabel label7; 
GLabel label8; 
GLabel label9; 
GLabel label10; 
GLabel label11; 
GCustomSlider gridSlider; 
GLabel label12; 
GWindow tutorial;
GButton next; 
GButton back; 
GButton finish; 
GWindow startWin;
GButton start; 
GButton tutButton; 
GButton libraryButton; 
GButton exit; 
GWindow library;
GButton closeLib; 
GWindow ArrGUI;
GButton aguiback; 
GLabel ArrangementType; 
GDropList arrTypedroplist; 
GCustomSlider X_Spacing; 
GCustomSlider Y_Spacing; 
GLabel Spacing_Labels; 
GLabel SizeSliders; 
GCustomSlider arrwidthslider; 
GCustomSlider arrheightslider; 
GButton addLibraryButton; 
GButton patternSave; 


  public void settings() { size(500, 500); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "--full-screen", "--bgcolor=#666666", "--hide-stop", "Modello" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
